package org.example.tests;

// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import java.util.HashMap;
import java.util.Map;

public class MyTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "/home/pedromgsouto/Documents/Uni/sel-chrome/chromedriver");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void RegisterSequence() {
        driver.get("https://www.toptal.com/");
        driver.manage().window().setSize(new Dimension(1920, 1014));
        driver.findElement(By.linkText("Apply as a Freelancer")).click();
        {
            WebElement element = driver.findElement(By.linkText("Sign in with LinkedIn"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        js.executeScript("window.scrollTo(0,41)");
        driver.findElement(By.id("talent_create_applicant_full_name")).click();
        driver.findElement(By.id("talent_create_applicant_full_name")).sendKeys("Pedro Souto");
        driver.findElement(By.id("talent_create_applicant_email")).sendKeys("pedromgsouto@ua.pt");
        driver.findElement(By.id("talent_create_applicant_password")).sendKeys("pass123");
        driver.findElement(By.id("talent_create_applicant_password_confirmation")).sendKeys("pass123");
    }
}
